labeled_num: 1000
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    main()
  File "main.py", line 80, in main
    Trainer.train(args,wandb,logging)
  File "/media/luckie/vol4/semi_supervised_cls/code/chest_code/trainer.py", line 98, in train
    Trainer.epochTrain(args, wandb, model, epoch, dataLoaderTrain, optimizer, scheduler,loss_fn)
  File "/media/luckie/vol4/semi_supervised_cls/code/chest_code/trainer.py", line 119, in epochTrain
    varOutput = model(varInput)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/luckie/vol4/semi_supervised_cls/code/chest_code/models.py", line 27, in forward
    x = self.densenet121(x)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torchvision/models/densenet.py", line 155, in forward
    features = self.features(x)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torchvision/models/densenet.py", line 74, in forward
    new_features = layer(*features)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/luckie/anaconda2/envs/py37/lib/python3.7/site-packages/torchvision/models/dens